dist: bionic

language: cpp

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - pip install --user cpp-coveralls

script:
  - make WITH_COVERAGE=1
  - cd testpp
  - ./run.sh
  - cd ..
  - make gcov

after_success:
  - coveralls -n --include threadmgr --include threadmgrpp
