#
#   Defines
#
BASEDIR		:=	../

INCLUDES	:= \
	-I./ \

LIBS		:= \
	-lpthread \

USERDEFS	:=	-D_MULTI_REQUESTING

#
#   Target object
#
TARGET_NAME	:=	threadmgr

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:= \
	threadmgr.c \
	threadmgr_if.c \
	threadmgr_util.c \


#
#   Configurations
#
include $(BASEDIR)/Config.make
